version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:812614658780:task-definition/prod-tf"
        LoadBalancerInfo:
          ContainerName: "prod-container"
          ContainerPort: 8080